config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :tasks
  post 'projects/:id/member' => 'projects#add_member_to_project'
  root "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  has_many :tasks
  has_many :user_to_projects
  # has_many :users, :through => :user_to_projects
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :owner, class_name: User, foreign_key: :owner_id
  belongs_to :requester, class_name: User, foreign_key: :requester_id
  belongs_to :parent, :class_name => Task, :foreign_key => "parent_id"
  has_many :children, :class_name => Task, :foreign_key => "parent_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects

  has_many :user_to_projects
  # has_many :projects, :through => :user_to_projects
  has_many :task
end

app/models/user_to_project.rb
class UserToProject < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper ProjectsHelper
  before_action :authenticate_user!
  def index
  @projects = current_user.projects
    @project_member = current_user.user_to_projects.joins(:project)
  end
  def new
    @project = Project.new
  end
  def show
    @project = Project.find(params[:id])
    @first_level_tasks = @project.tasks.where(:parent => nil)
  end
  def create
    @project = current_user.projects.create(params_project)
    if @project.save
      redirect_to project_path(@project)
      flash[:success] = "Project created!"
    else
      flash[:error] = "Lol"
    end
  end
  def add_member_to_project
    if User.where(:email=> "#{params['email']}").length > 0 && Project.find(params['project_id']).user.email != params['email']
      @add_user_to_project = UserToProject.create(user: User.where(:email=> "#{params['email']}").first, project_id: params['project_id'])
      redirect_to :back
    else
      p "sdfsdf"
      render :json => {arrors: 'errors'}
    end
  end

  private
  def params_project
    params.require(:project).permit( :name, :description )
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  def index
    # @projects = current_user.projects
  end
  def new
    @task = Task.new
  end
  def show
    @task = Task.find(params[:id])
  end
  def edit
    @task = Task.find(params[:id])
  end
  def create
    @task = Task.create(params_task)
    if @task.save
      redirect_to  task_path(@task)
      flash[:success] = "task created!"
    else
      flash[:error] = "Lol"
    end
  end
  def update
    @task = Task.find(params[:id])
    if @task.update(params_task)
      redirect_to  task_path(@task)
      flash[:success] = "update!"
    else
      flash[:error] = "Lol"
    end
  end
  private
  def params_task
    params.require(:task).permit(:title, :description, :status, :requester_id, :parent_id, :owner_id, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def iterrate_tasks(tasks, level=0, &block)
    tasks.each do |task|
      yield(task, level)
      if task.children
        iterrate_tasks(task.children, level+1, &block)
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MissionPossible
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if current_user
      %nav.navbar.navbar-default
        .container-fluid
          .navbar-header
            .navbar-text
              = link_to "Mission Possible", root_path
          .navbar-btn
            = link_to 'Log out', destroy_user_session_path, method: 'delete', class: 'pull-right btn btn-default'
    = yield

app/views/projects/_form_for.html.haml
=form_for @project do |f|
  .name_project
    = f.text_field :name, placeholder: 'Name'
  %br
  .description_project
    = f.text_field :description, placeholder: 'Description'
  %br
  =f.submit

app/views/projects/_member_modal.html.haml
.modal.member.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h4.modal-title Add member to project
      .modal-body
        %input{type: :email}
        %input{type: :hidden, :class => 'project_id', "data-id"=>  project.id}
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary.confirm_member{:type => "button", data_project: params[:project_id]} Save changes
    / /.modal-content
  / /.modal-dialog
/ /.modal

app/views/projects/_task_modal.html.haml
.modal.task.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h4.modal-title Create task
      .modal-body
        =form_for Task.new do |f|
          .name_project
            = f.text_field :title, placeholder: 'title'
            %br
            = f.text_area :description, placeholder: 'description', size: '60x12'
            %br
            = f.select :requester_id do
              -project.user_to_projects.joins(:user).each do |user|
                = content_tag(:option, user.user.email, value: user.user.id)
              =content_tag(:option, project.user.email, value: project.user.id )
            %br
            = f.select :status do
              =content_tag(:option, 'new', value: 'new')
              =content_tag(:option, 'started', value: 'started')
              =content_tag(:option, 'delivered', value: 'delivered')
              =content_tag(:option, 'rejected', value: 'rejected')
              =content_tag(:option, 'closed', value: 'closed')
            = f.hidden_field :owner_id, value: current_user.id
            = f.hidden_field :project_id, value: project.id
            = f.hidden_field :parent_id, value: ''
          %br
          =f.submit(class: 'btn btn-primary confirm_task')

          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/projects/index.html.haml
.all_proj
  .row
    .col-md-8
      %b Name
      .pull-right
        %b
          Creator
      %br
      -@projects.each do |project|
        =link_to project.name, project_path(project)
        .pull-right
          =" #{project.user.email}"

        %br
      -@project_member.each do |project|
        =link_to project.project.name, project_path(project)
        .pull-right
          ="#{project.project.user.email}"

        %br
    .col-md-4
      = link_to "create project", new_project_path, :class => 'Proj_create'
      %br

app/views/projects/new.html.haml
.cont
  =render 'form_for'

app/views/projects/show.html.haml
.proj
  .col-md-3
    %b
      Project Name
    %br
    =@project.name
    %br
    %br
    %b
      Project Description
    %br
    =@project.description
  .col-md-5
    %b
      Tasks
    %br
    .row
      .lvl0.task

        .col-md-3
          %b
            Title
        .col-md-4
          %b
            Requestor
        .col-md-2
          %b
            Status
        .col-md-3

        %br
      - if @project.tasks
        -#- iterrate_tasks(@first_level_tasks) do |task, level|
        - @project.tasks.where(parent_id: nil).each do  |task|
          .task
            .col-md-3
              =link_to task.title, task_path(task.id)
            .col-md-4
              =task.requester.email
            .col-md-2
              =task.status
            .col-md-3
              =link_to 'Create Task', '#', :class=> 'create_task_to_task', "data-task"=>task.id
            %br
            -#.task{:class=>"lvl#{level}"}
  .col-md-4
    %br
    =link_to '+ Member', '#', :class=> 'add_member'
    %br
    =link_to 'Create Task', '#', :class=> 'create_task'
    %br
    %br
    %b
      Member
    %br
    =@project.user.email
    %br
    - @project.user_to_projects.joins(:user).each do |user|
      =user.user.email
      %br
  =render 'task_modal', project: @project
  =render 'member_modal', project: @project

app/views/tasks/edit.html.haml
.proj
  .form_task
    =form_for @task, html: { method: :put } do |f|
      .name_project
        = f.text_field :title, placeholder: 'title'
        %br
        = f.text_area :description, placeholder: 'description', size: '60x12'
        %br
        = f.select :requester_id do
          -@task.project.user_to_projects.joins(:user).each do |user|
            = content_tag(:option, user.user.email, value: user.user.id)
          =content_tag(:option, @task.project.user.email, value: @task.project.user.id )
        %br
        = f.select :status do
          =content_tag(:option, 'new', value: 'new')
          =content_tag(:option, 'started', value: 'started')
          =content_tag(:option, 'delivered', value: 'delivered')
          =content_tag(:option, 'rejected', value: 'rejected')
          =content_tag(:option, 'closed', value: 'closed')
        = f.hidden_field :owner_id, value: current_user.id
        = f.hidden_field :parent_id, value: ''
      %br
      =f.submit

app/views/tasks/show.html.haml
.proj
  %b
    = "Title: #{@task.title}"
  %br
  = "Description: #{@task.description}"
  %br
  = "Requester: #{@task.requester.email}"
  %br
  = "Owner: #{@task.owner.email}"
  %br
  = "Status: #{@task.status}"
  %br
  - if current_user == @task.requester|| @task.owner
    =link_to 'Edit task', edit_task_path(@task.id)
    %br
    =link_to 'Create Task', '#', :class=> 'create_task_to_task', "data-task"=>@task.id

  %br
  .task_child
    -@task.children.each do |task|
      .children
        = "Title:"
        =link_to task.title, task_path(task)
        %br
        = "Description: #{task.description}"
        %br
        = "Requester: #{task.requester.email}"
        %br
        = "Status: #{task.status}"
        %br
        = "Owner: #{task.owner.email}"

  =render 'projects/task_modal', project: @task.project